#Example:

[[domains]]
domain = "https://gurka.se"
useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/triincir/"
#useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/squincir/"
#useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/penincir/"
#useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/octincir/"
#useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/tanincir/"
#useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/domincir/"
#useCrawler = false

#[[domains]]
#domain = "https://erich-friedman.github.io/packing/lincir/"
#useCrawler = false
